### ISSUE TITLE
Could not find a part of the path 'C:\temp\taiko.tmp'

### ISSUE THREAD

**Issue by bubbeh** [godteri/Taiko-Encryption-Tool#1]
Really good guide, worked very well. Nice job.

Very minor but I believe your application doesn't create a temp folder used while encrypting data. If the folder doesn't exist, it will crash.

```
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\temp\taiko.tmp'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.Create(String path)
   at TaikoEncryptionTool.Cryptgraphy.CreateZipText(String path, AesKeyType type)
   at TaikoEncryptionTool.Program.Main(String[] args)
```

**Comment by godteri** [comment]
Thanks for reporting, should be fixed now!
